#!/bin/bash
# --------------------------------------------------------------------------
# This script installs files and services specific to this project.
#
# Author: Bernhard Bablok
# License: GPL3
#
# Website: https://github.com/bablokb/gpio-poll-service
#
# --------------------------------------------------------------------------

# --- defaults used during installation   ----------------------------------

# --- basic packages   ------------------------------------------------------

PACKAGES=""
if [ -n "$PACKAGES" ]; then
  apt-get update
  apt-get -y install $PACKAGES
fi

# --- install specific files   ----------------------------------------------

for f in `find $(dirname "$0")/../files/ -type f`; do
  cp "$f" "${f#*files}"
  chown root:root "${f#*files}"
done
chmod 755 /usr/local/sbin/gpio-poll.py
chmod 644 /etc/gpio-poll.conf
chmod 644 /etc/systemd/system/gpio-poll.service

# --- activate service   ----------------------------------------------------

systemctl enable gpio-poll.service

# --- final configuration is manual   ---------------------------------------

echo -e "\n### Please edit /etc/gpio-poll.conf and start gpio-poll.service"

